---
title: "Project"
author: "Connor Simpson"
date: "04/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require('raster')
library(ncdf4)
library(forecast)
filter = stats::filter
lag = stats::lag
```

```{r}
ncpath =  ""
ncname <- "IMOS_ANMN-NRS_WZ_20180731T075900Z_NRSDAR_FV01_NRSDAR-1807-SUB-Sentinel-or-Monitor-Workhorse-ADCP-16.6_END-20190213T215900Z_C-20190402T064217Z"  
ncfname <- paste(ncpath, ncname, ".nc", sep="")
```

```{r}
ncin <- nc_open(ncfname)
```

```{r}
ncpath2 = ""
ncname2 <- "IMOS_ANMN_M_20180801T000000Z_NRSDAR_FV01"
ncfname2 <- paste(ncpath2, ncname2, ".nc", sep="")
ncin2 <- nc_open(ncfname2)
```
```{r}
WSPD = ncvar_get(ncin2,"WSPD_30min")
WSPD = WSPD[-1]
TIMEx = ncvar_get(ncin2,'TIME')
a <- 1:120
WSPDX <- WSPD[seq(1, length(WSPD), 4)]

```
2018-07-31T07:59:00Z
2018-08-01T07:30:00Z

```{r}
WWSH <- ncvar_get(ncin,"WWSH")
WWSH = WWSH[-(0:12)]
TIME <- ncvar_get(ncin,"TIME")
TIME = TIME[-(0:12)]
WWSHb = WWSH[1:369]

```


```{r}
acf(WWSH)
pacf(WWSH,lag.max=40)
```
Basic Cross validation using ARIMA and origianl time series
```{r}
k = 4
h = 50
v = as.integer(length(WWSH)/(2*k))
size = 2*v+1
error = rep(NA,(k-1))
for (i in (0:(k-1))){
  if (i == 0){z = 0}
  else{z=1}
    if (i == k-1){z2 = 0}
  else{z2=1}
  test = rep(NA,length(WWSH))
  train = WWSH
  test[((size)*i+1):((size)*i+size)] = WWSH[((size)*i+1):((size)*i+size)]
  train[((size)*i+1-h*z):((size)*i+size+h*z2)] = NA
  plot.ts(test,col=2)
  lines(train,col=3)
  mod = Arima(train,order = c(6,1,3))
  modt = Arima(test,model = mod)
  error[i+1] = accuracy(modt)[2]
}
```

```{r}
plot(mod$fitted)
```



Basic test of ARIMAX
```{r}
modelx = Arima(WWSHb,order=c(5,1,0),xreg=WSPDX)
```


```{r}
summary(modelx)
```



Example with differenced time series
```{r}
tsdiff = diff(WWSH)
```

```{r}
k = 4
h = 50
v = as.integer(length(tsdiff)/(2*k))
size = 2*v+1
error = rep(NA,(k-1))
for (i in (0:(k-2))){
  if (i == 0){z = 0}
  else{z=1}
    if (i == k-1){z2 = 0}
  else{z2=1}
  test = rep(NA,length(tsdiff))
  train = tsdiff
  test[((size)*i+1):((size)*i+size)] = tsdiff[((size)*i+1):((size)*i+size)]
  train[((size)*i+1-h*z):((size)*i+size+h*z2)] = NA
  plot.ts(test,col=2)
  lines(train,col=3)
  mod = Arima(train,order = c(6,1,3))
  modt = Arima(test,model = mod)
  error[i+1] = accuracy(modt)[2]
}
```




