---
title: "PearsonR"
author: "Connor Simpson"
date: "09/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
data4 = read.csv("bioChemAll43.csv")
```
```{r}
data42 =data4[-1]
head(data42)
```

```{r}
Rcoef = c()
for (i in 1:length(data42)){
  Rcoef[i] = abs(cor(data42[,"darwinBiochem_TEMP_0"],data42[i],use="pairwise.complete.obs"))
}
```

```{r}
Rcoef = data.frame(Rcoef,row.names = colnames(data42))

```


```{r}
Rcoef2 = c()
for (i in 1:length(data2)){
  Rcoef2[i] = abs(cor(data2[,"TEMP"],data2[i],use="pairwise.complete.obs"))
}
```

```{r}
Rcoef2 = data.frame(Rcoef2,row.names = colnames(data2))

```




```{r}
setwd("C:/Users/Connor Simpson/Desktop/New folder (2)/r/Rstuff/data2/data3")
dataccf = read.csv("BiochemWind.csv")
dataccf = dataccf[-1]
```
```{r}
Rcoefccf = c()
for (i in 1:length(dataccf)){
  Rcoefccf[i] = abs(cor(dataccf[,"CNDC"],dataccf[i],use="pairwise.complete.obs"))
}
```

```{r}
Rcoefccf = data.frame(Rcoefccf,row.names = colnames(dataccf))

```












