---
title: "ARIMAtemp"
author: "Connor Simpson"
date: "10/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(forecast)
library(Metrics)
library(tseries)
accuracy = forecast::accuracy
```

```{r}
data = read.csv("darwinBiochem.csv")
```

```{r}
TEMP = data[,"TEMP"]
CNDC = data[,'CNDC']
TURB = data[,"TURB"]
PAR = data[,"PAR"]
CPHL = data[,"CPHL"]
```


```{r}
antidiff = function(orig,diffed){
  return(orig[-length(orig)]+diffed)
}
```

WMAPE
REMOVE ABS ON SUM(TRU)
```{r}
WMAPE <- function(pred,tru){
  WMAPE = sum(abs(pred-tru),na.rm = T)/sum(tru,na.rm = T)
  return(WMAPE)
}
```


reler
```{r}
reler <- function(pred,tru,bench){
  reler = sum(abs(tru-pred),na.rm = T)/sum(abs(tru-bench),na.rm = T)
  return(reler)
}
```

rsq 
```{r}
rsq <- function(pred,tru){
  SSE = sum((tru-pred)^2,na.rm = T)
  SS = sum((tru-mean(na.omit(tru)))^2,na.rm = T)
  rsq = 1- SSE/SS
  return(rsq)
}
```


adjr
```{r}
adjr <- function(pred,tru,coefnum){
  rs = rsq(pred,tru)
  n = length(pred)
  adjr = 1-(1-rs)*(n-1)/(n-coefnum-1)
  return(adjr)
}
```

rmse
```{r}
rootMSE = function(pred,tru){
  return(sqrt(mean((pred-tru)^2,na.rm = T)))
}
```


```{r}
crossvalid <- function(ts,exog,k,h,order,tsori){
  pred = data.frame(ts)
  tru = data.frame(ts)
  arsq=0
  WMAPE=0
  rmse=0
  reler=0
  v = as.integer(length(ts)/(2*k))
  size = 2*v
  error = rep(NA,(k-1))
  for (i in (0:(k-1))){
    if (i == 0){z = 0}
    else{z=1}
      if (i == k-1){z2 = 0}
    else{z2=1}
    test = rep(NA,length(ts))
    testx = data.frame(exog)
    for (bb in (1:length(exog))){
      testx[bb] = c(rep(NA,length(exog[,bb])))
    }
    train = ts
    trainx = exog
    test[((size)*i+1):((size)*i+size)] = ts[((size)*i+1):((size)*i+size)]
    for (m in (1:length(testx))){
      testx[((size)*i+1):((size)*i+size),m] = exog[((size)*i+1):((size)*i+size),m]
    }
    train[((size)*i+1-h*z):((size)*i+size+h*z2)] = NA
    for (b in (1:length(trainx))){
      trainx[((size)*i+1-h*z):((size)*i+size+h*z2),b] = NA
    }
    mod = Arima(train,order = order,xreg = trainx,include.constant = F)
    modt = Arima(test,model = mod,xreg=testx,include.constant = F)
    error[i+1] = accuracy(modt)[2]
    coefnum = length(mod$coef)
    pred1 = modt$fitted
    tru1 = test
    #print(length(tsori))
    #print(length(pred1))
    #print(length(tru1))
    pred = antidiff(tsori,pred1)
    tru = antidiff(tsori,tru1)
    
    
    
    #plot.ts(pred,col=2)
    #plot.ts(tru,col=4)
    #plot.ts(tru-pred)
    #print(sum(abs(tru),na.rm=T))
    #print(sum(abs(tru-pred),na.rm=T))
    arsq[i+1] = adjr(pred,tru,coefnum)
    WMAPE[i+1] = WMAPE(pred,tru)
    rmse[i+1] = rootMSE(tru,pred)
    bench = tru[-length(tru)]
    trub = tru[-1]
    predb = pred[-1]
    reler[i+1] = reler(predb,trub,bench)
    #print(arsq)
    #pred[i+1] = modt$fitted
    #tru[i+1] = test
  }
  return(data.frame(arsq,WMAPE,rmse,reler))
  #return(data.frame(pred,tru))
}
```

```{r}
crossvalidnox <- function(ts,k,h,order,tsori){
  pred = data.frame(ts)
  tru = data.frame(ts)
  arsq=0
  WMAPE=0
  rmse=0
  reler=0
  v = as.integer(length(ts)/(2*k))
  size = 2*v
  error = rep(NA,(k-1))
  for (i in (0:(k-1))){
    if (i == 0){z = 0}
    else{z=1}
      if (i == k-1){z2 = 0}
    else{z2=1}
    test = rep(NA,length(ts))
    train = ts
    test[((size)*i+1):((size)*i+size)] = ts[((size)*i+1):((size)*i+size)]
    train[((size)*i+1-h*z):((size)*i+size+h*z2)] = NA
    mod = Arima(train,order = order,include.constant = F)
    modt = Arima(test,model = mod,include.constant = F)
    error[i+1] = accuracy(modt)[2]
    coefnum = length(mod$coef)
    pred1 = modt$fitted
    tru1 = test
    #print(length(tsori))
    #print(length(pred1))
    #print(length(tru1))
    pred = antidiff(tsori,pred1)
    tru = antidiff(tsori,tru1)
    
    #plot.ts(train)
    #plot.ts(pred,col=2)
    #plot.ts(tru,col=4)
    #plot.ts(tru-pred)
    #print(sum(abs(tru),na.rm=T))
    #print(sum(abs(tru-pred),na.rm=T))
    arsq[i+1] = adjr(pred,tru,coefnum)
    WMAPE[i+1] = WMAPE(pred,tru)
    rmse[i+1] = rootMSE(tru,pred)
    bench = tru[-length(tru)]
    trub = tru[-1]
    predb = pred[-1]
    reler[i+1] = reler(predb,trub,bench)
    #print(arsq)
    #pred[i+1] = modt$fitted
    #tru[i+1] = test
  }
  return(data.frame(arsq,WMAPE,rmse,reler))
  #return(data.frame(pred,tru))
}
```



```{r}

er = c(0,0,0,0,0)
TEMPAR = data.frame(er)
TEMPMA = data.frame(er)
for (i in (1:10)){
  TEMPAR[i] = as.matrix(crossvalidnox(diff(TEMP),5,100,c(i,0,0),TEMP))
}
for (i in (1:10)){
  TEMPMA[i] = as.matrix(crossvalidnox(diff(TEMP),5,100,c(0,0,i),TEMP))
}
```



```{r}

er = c(0,0,0,0,0)
TEMPARCNDC = data.frame(er)
TEMPMACNDC = data.frame(er)
for (i in (1:10)){
  TEMPARCNDC[i] = as.matrix(crossvalid(diff(TEMP),data.frame(diff(CNDC)),5,100,c(i,0,0),TEMP))
}
for (i in (1:10)){
  TEMPMACNDC[i] = as.matrix(crossvalid(diff(TEMP),data.frame(diff(CNDC)),5,100,c(0,0,i),TEMP))
}
```


```{r}

er = c(0,0,0,0,0)
TEMPARPAR = data.frame(er)
TEMPMAPAR = data.frame(er)
for (i in (1:10)){
  TEMPARPAR[i] = as.matrix(crossvalid(diff(TEMP),data.frame(diff(PAR)),5,100,c(i,0,0),TEMP))
}
for (i in (1:10)){
  TEMPMAPAR[i] = as.matrix(crossvalid(diff(TEMP),data.frame(diff(PAR)),5,100,c(0,0,i),TEMP))
}
```



```{r}

er = c(0,0,0,0,0)
TEMPARTURB = data.frame(er)
TEMPMATURB = data.frame(er)
for (i in (1:10)){
  TEMPARTURB[i] = as.matrix(crossvalid(diff(TEMP),data.frame(diff(TURB)),5,100,c(i,0,0),TEMP))
}
for (i in (1:10)){
  TEMPMATURB[i] = as.matrix(crossvalid(diff(TEMP),data.frame(diff(TURB)),5,100,c(0,0,i),TEMP))
}
```


```{r}

er = c(0,0,0,0,0)
TEMPARCPHL = data.frame(er)
TEMPMACPHL = data.frame(er)
for (i in (1:10)){
  TEMPARCPHL[i] = as.matrix(crossvalid(diff(TEMP),data.frame(diff(CPHL)),5,100,c(i,0,0),TEMP))
}
for (i in (1:10)){
  TEMPMACPHL[i] = as.matrix(crossvalid(diff(TEMP),data.frame(diff(CPHL)),5,100,c(0,0,i),TEMP))
}
```



#########################################

```{r}

er = c(0,0,0,0,0)
CNDCAR = data.frame(er)
CNDCMA = data.frame(er)
for (i in (1:10)){
  CNDCAR[i] = as.matrix(crossvalidnox(diff(CNDC),5,100,c(i,0,0),CNDC))
}
for (i in (1:10)){
  CNDCMA[i] = as.matrix(crossvalidnox(diff(CNDC),5,100,c(0,0,i),CNDC))
}
```



```{r}

er = c(0,0,0,0,0)
CNDCARTEMP = data.frame(er)
CNDCMATEMP = data.frame(er)
for (i in (1:10)){
  CNDCARTEMP[i] = as.matrix(crossvalid(diff(CNDC),data.frame(diff(TEMP)),5,100,c(i,0,0),CNDC))
}
for (i in (1:10)){
  CNDCMATEMP[i] = as.matrix(crossvalid(diff(CNDC),data.frame(diff(TEMP)),5,100,c(0,0,i),CNDC))
}
```


```{r}

er = c(0,0,0,0,0)
CNDCARPAR = data.frame(er)
CNDCMAPAR = data.frame(er)
for (i in (1:10)){
  CNDCARPAR[i] = as.matrix(crossvalid(diff(CNDC),data.frame(diff(PAR)),5,100,c(i,0,0),CNDC))
}
for (i in (1:10)){
  CNDCMAPAR[i] = as.matrix(crossvalid(diff(CNDC),data.frame(diff(PAR)),5,100,c(0,0,i),CNDC))
}
```



```{r}

er = c(0,0,0,0,0)
CNDCARTURB = data.frame(er)
CNDCMATURB = data.frame(er)
for (i in (1:10)){
  CNDCARTURB[i] = as.matrix(crossvalid(diff(CNDC),data.frame(diff(TURB)),5,100,c(i,0,0),CNDC))
}
for (i in (1:10)){
  CNDCMATURB[i] = as.matrix(crossvalid(diff(CNDC),data.frame(diff(TURB)),5,100,c(0,0,i),CNDC))
}
```


```{r}

er = c(0,0,0,0,0)
CNDCARCPHL = data.frame(er)
CNDCMACPHL = data.frame(er)
for (i in (1:10)){
  CNDCARCPHL[i] = as.matrix(crossvalid(diff(CNDC),data.frame(diff(CPHL)),5,100,c(i,0,0),CNDC))
}
for (i in (1:10)){
  CNDCMACPHL[i] = as.matrix(crossvalid(diff(CNDC),data.frame(diff(CPHL)),5,100,c(0,0,i),CNDC))
}
```

```{r}
plot.ts(diff(TEMP)[0:70000])
```




```{r}
Acf(diff(TEMP))
Pacf(diff(TEMP))
```



```{r}
avWWSHAR = data.frame(row.names=c('arsq','WMAPE','rmse','reler'))
wwshdata = CNDCMACPHL
for (i in (1:4)){
  errora = c()
  sder = c()
  for (j in (1:length(wwshdata))){
    errora[j] = mean(wwshdata[,j][,i])
    sder[j] = sd(wwshdata[,j][,i])
  }
  if (i == 1){
    error = max(errora)
    order = which.max(errora)
    sder2 = sder[order]
  }
  else{
  error = min(errora)
  order = which.min(errora)
  sder2 = sder[order]
  }
  
  avWWSHAR[i,1] =error
  avWWSHAR[i,2] =order
  avWWSHAR[i,3] =sder2
}
colnames(avWWSHAR) = c('error','order','sd')
```






